site_name: Incidents
site_url: https://eg-etcs.github.io/incident/
theme:
  favicon: alarm.png
  logo: alarm.png
  name: material
  icon:
    annotation: material/arrow-right-circle
  features:
    # - toc.integrate
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.tracking
    - content.math
    - navigation.tabs.sticky
    
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
    
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocs-pdf
  - mkdocs-video:
      is_video: True
      video_muted: False
      is_video: True
      video_controls: True
      css_style:
        width: "100%"


nav:
  - Today's Incidents:
    - index.md
  - This Week:
    - This-Week.md
  - Last Week:
    - Last-Week.md
  - Incidents:
    - "": default.md
    - "2025" : 
      - "October": 
        - "week44": 
          - "Nihon Kohden CNS-6201": Week44/nihon-kohden-cns-6201.md
          - "ASKI Energy ALS-Mini": Week44/aski-energy-als-mini.md
          - "Delta Electronics ASDA-Soft": Week44/delta-electronics-asda-soft.md
          - "Windows Server WSUS": Week44/windows-server-wsus.md
          - "BlueNoroff Campaigns": Week44/bluenoroff-ghostcall-ghosthire.md
          - "Everest AT&T Aviation Leaks": Week44/everest-att-aviation-leaks.md
          - "HSBC USA Data Breach": Week44/hsbc-usa-data-breach.md
          - "Vertikal Hospital Manager": Week44/vertikal-hospital-manager.md
      - "November": 
         - "week45": 
            - "Cisco IOS XE": Week45/Cisco-IOS-XE.md
            - "VMware Aria Operations and VMware Tools": Week45/VMware-tools.md
            - "Android/BankBot-YNRK malware": Week45/Android-BankBot.md
            - "Cisco ASA Secure Firewall":  Week45/Cisco-ASA.md
            - "Multiple Critical Vulnerabilities in Moxa": Week45/Moxa.md
            - "Super Value Co. Ransomware Breach" : Week45/Super-Value.md
            - "Android Security Bulletin": Week45/Android-Security-Bulletin.md
            - "Cyber Toufan – Maya Engineering Surveillance Breach" : Week45/maya-engineering-breach.md
         - "week46":
            - "Samsung Mobile Zero-Day Exploited to Deploy LANDFALL Spyware": Week46/samsung-spyware.md
            - "Cisco Unified Contact Center Express (Unified CCX) Vulnerabilities": Week46/cisco-ccx.md
            - "Multiple Vulnerabilities in Apple Products": Week46/apple.md
            - "ABB FLXeon Controllers Vulnerabilities": Week46/abb-fbxi.md
            - "Delhi Airport GPS Spoofing Crisis": Week46/delhi.md
            - "ClickFix Hospitality Phishing Campaign": Week46/clickfix.md
            - "Actively Exploited Windows Kernel Zero‑Day": Week46/kernel.md
            - "Whisper Leak — LLM Side‑Channel Attack": Week46/whisper.md
            - "Google vs. Lighthouse Phishing-as-a-Service Operation": Week46/Lighthouse.md
         - "week47":
            - "Fortinet FortiWeb Authentication Bypass": Week47/fortiweb.md
            - "Critical IBM AIX NIM Vulnerabilities": Week47/aix.md
            - "D‑Link DIR-816L": Week47/dlink.md
            - "Microsoft Graphics Component Vulnerability – CVE-2025-60724": Week47/ms-gfx.md
            - "Google Chrome V8 Zero-Day – CVE-2025-13223": Week47/chrome-v8.md
            - "Lynx+ Gateway Critical Vulnerabilities": Week47/lynx.md
            - "FortiWeb OS Command Injection (CVE-2025-58034)": Week47/fortiwebzero.md
         - "week48":
            - "ABB Ability Edgenius – Authentication Bypass (CVE-2025-10571)": Week48/abb.md
            - "Oracle Fusion Middleware – Missing Authentication for Critical Function (CVE-2025-61757)": Week48/oracle.md
            - "China-Linked APT31 Stealth Cyberattacks on Russian IT – Using Cloud Services": Week48/apt31.md
            - "Oracle EBS Zero-Day Exploitation – CVE-2025-61882": Week48/oracle-ebs.md
            - "CISA Warning: Spyware Campaigns Targeting Messaging App Users": Week48/spyware.md
            - "Festo Compact Vision System – Insecure Configuration Vulnerabilities": Week48/festo.md
            - "ShadowV2 IoT Botnet Opportunistic Attack During AWS Outage": Week48/shadowV2.md
         - "week49":
            - "node-forge ASN.1 Validation Bypass Vulnerability": Week49/forge.md
            - "Contagious Interview (2025 npm-registry wave)": Week49/npm.md
            - "OpenPLC ScadaBR CVE-2021-26829 Active Exploitation": Week49/openplc.md
            - "Scada-LTS Project Import Path Traversal – CVE-2025-13791": Week49/scadalts.md
            - "Mercedes-Benz USA Breach Claim by Threat Actor 'zestix'": Week49/benz.md
            - "OnSolve CodeRED Ransomware Attack": Week49/onsolve.md
            - "MuddyWater MuddyViper Backdoor Campaign": Week49/muddy.md
            - "Hacking of ~120,000 IP Cameras in South Korea for Sale of Intimate Content": Week49/knpa.md
      - "December":
         - "week50":
            - "GoldFactory Hits Southeast Asia with Modified Banking Apps Driving 11,000+ Infections": Week50/goldfactory.md
            - "WhatsApp-Based Malware Campaign by Water Saci": Week50/watersaci.md
            - "Johnson Controls FX80 / FX90 Vulnerability (CVE-2025-43867)": Week50/johnson.md
            - "React2Shell (CVE-2025-55182)": Week50/react2shell.md
            - "UDPGangster Campaigns Target Multiple Countries": Week50/muddyudp.md
            - "Android Malware Surge: FvncBot, SeedSnatcher, and Upgraded ClayRat": Week50/andSurge.md
            - "ArrayOS AG VPN (CVE-2025-66644)": Week50/arrayos.md
         - "week51":
            - "GeoServer XXE Vulnerability Exploitation (CVE-2025-58360)": Week51/geoserver.md
            - "CVE-2018-4063 Sierra Wireless AirLink ALEOS Remote Code Execution": Week51/sierra.md
            - "Pro-Russia Hacktivists Conduct Opportunistic Attacks Against Critical Infrastructure": Week51/hacktivists.md
            - "Google Chromium Out-of-Bounds Memory Access Vulnerability": Week51/chromium.md
            - "Johnson Controls iSTAR Ultra Vulnerabilities": Week51/istar.md
            - "Siemens Energy Services Security Advisory": Week51/siemensesa.md
            - "Apple Multiple Products Use-After-Free WebKit Vulnerability": Week51/useAfterFree.md
            - "Fortinet FortiCloud SSO Login Authentication Bypass Vulnerabilities": Week51/forticloud.md
            - "SolarEdge SE3680H Contains Linux Kernel Vulnerabilities": Week51/solaredge.md
            - "Russian GRU Cyber Campaign Targeting Critical Infrastructure via Edge Network Devices": Week51/RussianGRU.md
            - "OS Command Injection in Fortinet FortiSandbox": Week51/sandbox.md
            - "Cisco AsyncOS Zero-Day Exploitation Campaign": Week51/AsyncOS.md
            - "ASUS Live Update Embedded Malicious Code Vulnerability": Week51/asus.md
            - "SonicWall SMA1000 Zero-Day Vulnerabilities": Week51/sonicWall.md
         - "week52":
            - "CVE-2025-14993: Tenda AC18 Router Stack Buffer Overflow'": Week52/ac18.md
            - "WatchGuard Firebox Fireware OS IKEv2 Out-of-Bounds Write Vulnerability": Week52/watchguard.md
            - "U.S. DOJ Charges 54 in ATM Jackpotting Scheme Using Ploutus Malware" : Week52/doj.md
            - "Romanian Waters Authority Hit by Ransomware Attack": Week52/romanian.md
            - "Kimwolf Botnet: 1.8 Million Android Devices Hijacked": Week52/kimwolf.md
            - "China-Linked \"Ink Dragon\" APT Espionage Campaign": Week52/dragon.md
            - "Cyberattack on La Poste and La Banque Postale": Week52/laposte.md
            - "CVE-2025-68613: Critical n8n Remote Code Execution Vulnerability": Week52/n8n.md
            - "Lotusbail: Malicious npm Package Targeting WhatsApp Web API Developers": Week52/lotusbail.md
            - "MacSync macOS Stealer: Code-Signed Malware Bypassing Gatekeeper": Week52/macsync.md
            - "FBI Seizure of Fraud Domain Hosting Stolen Bank Credentials": Week52/fbi.md