site_name: Incidents
site_url: https://eg-etcs.github.io/incident/
theme:
  favicon: alarm.png
  logo: alarm.png
  name: material
  icon:
    annotation: material/arrow-right-circle
  features:
    # - toc.integrate
    - content.code.copy
    - content.code.annotate
    - navigation.tabs
    - navigation.tracking
    - content.math
    - navigation.tabs.sticky
    
  palette:

    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      toggle:
        icon: material/brightness-4
        name: Switch to light mode

extra_css:
  - stylesheets/extra.css
    
markdown_extensions:
  - attr_list
  - md_in_html
  - admonition
  - pymdownx.details
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - https://unpkg.com/mathjax@3/es5/tex-mml-chtml.js

plugins:
  - search
  - mkdocs-pdf
  - mkdocs-video:
      is_video: True
      video_muted: False
      is_video: True
      video_controls: True
      css_style:
        width: "100%"


nav:
  - Today's Incidents:
    - index.md
  - This Week:
    - This-Week.md
  - Last Week:
    - Last-Week.md
  - Incidents:
    - "": default.md
    - "2025" : 
      - "October": 
        - "week44": 
          - "Nihon Kohden CNS-6201": Week44/nihon-kohden-cns-6201.md
          - "ASKI Energy ALS-Mini": Week44/aski-energy-als-mini.md
          - "Delta Electronics ASDA-Soft": Week44/delta-electronics-asda-soft.md
          - "Windows Server WSUS": Week44/windows-server-wsus.md
          - "BlueNoroff Campaigns": Week44/bluenoroff-ghostcall-ghosthire.md
          - "Everest AT&T Aviation Leaks": Week44/everest-att-aviation-leaks.md
          - "HSBC USA Data Breach": Week44/hsbc-usa-data-breach.md
          - "Vertikal Hospital Manager": Week44/vertikal-hospital-manager.md
      - "Nov": 
         - "week45": 
            - "Cisco IOS XE": Week45/Cisco-IOS-XE.md
            - "VMware Aria Operations and VMware Tools": Week45/VMware-tools.md
            - "Android/BankBot-YNRK malware": Week45/Android-BankBot.md
            - "Cisco ASA Secure Firewall":  Week45/Cisco-ASA.md
            - "Multiple Critical Vulnerabilities in Moxa": Week45/Moxa.md
            - "Super Value Co. Ransomware Breach" : Week45/Super-Value.md
            - "Android Security Bulletin": Week45/Android-Security-Bulletin.md
            - "Cyber Toufan – Maya Engineering Surveillance Breach" : Week45/maya-engineering-breach.md
         - "week46":
            - "Samsung Mobile Zero-Day Exploited to Deploy LANDFALL Spyware": Week46/samsung-spyware.md
            - "Cisco Unified Contact Center Express (Unified CCX) Vulnerabilities": Week46/cisco-ccx.md
            - "Multiple Vulnerabilities in Apple Products": Week46/apple.md
            - "ABB FLXeon Controllers Vulnerabilities": Week46/abb-fbxi.md
            - "Delhi Airport GPS Spoofing Crisis": Week46/delhi.md
            - "ClickFix Hospitality Phishing Campaign": Week46/clickfix.md
            - "Actively Exploited Windows Kernel Zero‑Day": Week46/kernel.md
            - "Whisper Leak — LLM Side‑Channel Attack": Week46/whisper.md
            - "Google vs. Lighthouse Phishing-as-a-Service Operation": Week46/Lighthouse.md
         - "week47":
            - "Fortinet FortiWeb Authentication Bypass": Week47/fortiweb.md
            - "Critical IBM AIX NIM Vulnerabilities": Week47/aix.md
            - "D‑Link DIR-816L": Week47/dlink.md
            - "Microsoft Graphics Component Vulnerability – CVE-2025-60724": Week47/ms-gfx.md
            - "Google Chrome V8 Zero-Day – CVE-2025-13223": Week47/chrome-v8.md
            - "Lynx+ Gateway Critical Vulnerabilities": Week47/lynx.md
            - "FortiWeb OS Command Injection (CVE-2025-58034)": Week47/fortiwebzero.md
         - "week48":
            - "ABB Ability Edgenius – Authentication Bypass (CVE-2025-10571)": Week48/abb.md
            - "Oracle Fusion Middleware – Missing Authentication for Critical Function (CVE-2025-61757)": Week48/oracle.md
            - "China-Linked APT31 Stealth Cyberattacks on Russian IT – Using Cloud Services": Week48/apt31.md
            - "Oracle EBS Zero-Day Exploitation – CVE-2025-61882": Week48/oracle-ebs.md
            - "CISA Warning: Spyware Campaigns Targeting Messaging App Users": Week48/spyware.md
            - "Festo Compact Vision System – Insecure Configuration Vulnerabilities": Week48/festo.md
<<<<<<< HEAD
            - "ShadowV2 IoT Botnet Opportunistic Attack During AWS Outage": Week48/shadowV2.md
=======
>>>>>>> parent of 9ada367 (update 30/11)
